export const NavbarMenu =[
    {
        id:1,
        title:"Dashboard",
        link:"#"
    },
    {
        id:2,
        title:"Incidents",
        link:"#"
    },
    {
        id:3,
        title:"Locations",
        link:"#"
    },
    {
        id:4,
        title:"Activities",
        link:"#"
    },
    {
        id:5,
        title:"Documents",
        link:"#"
    },
    {
        id:6,
        title:"Cypher",
        link:"#"
    },
]